# My dictionary

## numpy

In [126]:
import numpy as np
import pandas as pd

#ARRAY 
arrays  =  np.array([[1,2,3],[4,5,6]])   # create an array with numpy
zeros   =  np.zeros((5,5))               # array of zero
ones    =  np.ones((5,5))                # array of one
full    =  np.full((5,5),zeros)          # full with any number
eye     =  np.eye(5)                     # indetify matrix
random  =  np.random.random((5,5))       # random numbers
arange  =  np.arange(18)                 #from number to number 
lins    =  np.linspace(0,10,2)           # from number to number the last element specify how many 
uniform =  np.random.rand(5)  *100       #random distribution
calcian =  np.random.randn(5) *100       #calcian distibution
intei   =  np.random.randint(0,1000,100) #randint 100 of [0-1000]
arredo  =  np.round(uniform,0)           #to int number,the second element specify hom many numbers after dot
reshape =  arange.reshape(3,6)           # use with  np.arange(18)  transfom shape from vector to matrix 
minn    =  reshape.min()                 #minimum number of array
maxn    =  reshape.max()                 #maximum number of array
indxmax =  reshape.argmax()              #index o max number
np.random.seed(101)                      #start with standard number




#PANDAS
numbers= np.arange(9)
go = pd.DataFrame(intei.reshape(10,10))         #drop element from matrix
go.drop(9,axis=0,inplace=True)                  #drop the line 9 
go.drop(9,axis=1,inplace=True)                  #drop the row 9 
go.loc[[0],[1]]                                 #find a specify element from matrix
go.loc[0][1]                                    #find a specify element from matrix
go.iloc[[0],[1]]                                #find a specify element from matrix by index
go["number"] = numbers







    





#MATH
add     =  np.add(eye,ones)         # add or x+y 
sub     =  np.subtract(eye,ones)    # asubtract or x-y  
mult    =  np.multiply(eye,ones)    # multiply or x*y  
div     =  np.divide(eye,ones)      # divide or x/y  
sqrt    =  np.sqrt(eye,ones)        # sqrt  
dot     =  np.dot(eye,ones)         # to multiply a vector by a matrix, and to multiply matrices
dot2    =  eye.dot(ones)            # anpther way to use dot 
sumAll  =  np.sum(arrays)           # compute the sum of all ementents in array
sumCol  =  np.sum(arrays,axis=0)    # sum of column
sumRow  =  np.sum(arrays,axis=1)    # sum of Row

In [130]:
go.reset_index()

   index    0    1    2    3    4    5    6    7    8  number
0      0  760  203  463  865  989  664  676  892  703       0
1      1  498  419  542   10  499  956  615  276  923       1
2      2  854  378  794  499  855  686   47  950  741       2
3      3  137  685  386  402  570  239   92  907  507       3
4      4  625  478  419  540    3  851  340  303  526       4
5      5  709  505  956  197  632  947  262  984  103       5
6      6  366   71  357  964  244  919  675  207  226       6
7      7  850  953  461   46  643  558  508  997  797       7
8      8  149  378   21  465  535  235  254  383   94       8

In [137]:
col.prop()

['BR', 'AUS', 'ARG', 'CAN', 'MEX', 'FRA', 'GREC', 'EUA']